### PR TITLE
Security: Address dependabot alerts

### PR DESCRIPTION
**Pull request by ianrohde**
## Summary of Changes:

This pull addresses all active dependabot alerts.

- Ran `npm audit fix` (unsucessfully updated)
- Ran `npm audit fix --force`

...which updated `lerna` to v4: https://github.com/lerna/lerna/releases/tag/v4.0.0

Sidenote: I had to install lerna globally to confirm `lerna bootsrap` was working after update

qa_req 0

### CODE REVIEW

**Review by bhuminson — APPROVED** [review]
CR :dagger:

**Comment by GrantMatejka** [comment]
CR :corn:

**Comment by k0rvusk0r4x** [comment]
Ideas for testing?

**Comment by ianrohde** [comment]
> Ideas for testing?

No testing ability on this one. Set qa_req accordingly

**Pull request merged**
